apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-config
  namespace: dev
data:
  config.yaml: |
    name: shop.api
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 1s
      grpc:
        addr: 0.0.0.0:9000
        timeout: 1s
    data:
      database:
        driver: mysql
        source: root:qwe123@tcp(0.0.0.0:3306)/shop?charset=utf8mb4&parseTime=True&loc=Local
      redis:
        addr: 0.0.0.0:6379
        read_timeout: 0.2s
        write_timeout: 0.2s
    trace:
      endpoint: http://0.0.0.0:14268/api/traces
    auth:
      jwt_key: hqFr%3ddt32DGlSTOI5cO6@TH#fFwYnP$S
    service:
      user:
        endpoint: discovery:///shop.users.service
      goods:
        endpoint: discovery:///shop.goods.service

