apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop
  annotations:
    # We are defining this annotation to prevent nginx
    # from redirecting requests to `https` for now
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mysql-cluster-ip
                port:
                  number: 3306
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-ip
                port:
                  number: 6379
